name: Deploy Python project to Azure Function App
# Deploys to the azure function app when a push is made from the backend

on:
  push:
      branches:
        - master
        - main
      paths:
        - 'backend_crc/**'

env:
  AZURE_FUNCTIONAPP_NAME: app-crcresumefxn   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

  COSMOSDB_ACC_NAME: ${{ vars.COSMOSDB_ACC_NAME}}
  COSMOSDB_CLIENT: ${{ vars. COSMOSDB_CLIENT}}
  COSMOSDB_CONT_NAME: ${{ vars. COSMOSDB_CONT_NAME}}
  COSMOS_ENDPOINT: ${{ vars. COSMOS_ENDPOINT}}
  COSMOS_KEY: ${{ vars. COSMOS_KEY}}



  

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Run the python tests
      run: |
        pip install azure-cosmos
        pushd Backend_CRC
        python tests.py
        popd


    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true